[workspace]
members = [
    "cyber_crush_authentication_server",
    "cyber_crush_bank_server",
    "cyber_crush_chat_server",
    "cyber_crush_data_server", "cyber_crush_news_server",
    "shared_server_lib"
]
